version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:25000
    environment:
      - DB_USER=user
      - DB_PASSWORD=12345
      - DB_NAME=db_name
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=db_name
