version: '3.3'

services:
  app:
    image: serafimserbinovich/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8080:25000
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=db_name
